# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1or2xJg_zAH2O5I5s9Vb_1808b3ITMvwU
"""

! python /content/download.py --exp imagenet

! pip install -e
! pip install numpy==1.24.0 matplotlib==3.6.2 scikit-image==0.19.3 scikit-learn==1.2.0 gdown==4.6.0
! pip install mpi4py openmpi

pip install blobfile

# 修改模型和数据集的路径
model_path = "/content/drive/MyDrive/Projects/ddib-main/ddib-main/models/imagenet/256x256_diffusion.pt"
classifier_path = "/content/drive/MyDrive/Projects/ddib-main/ddib-main/models/imagenet/256x256_classifier.pt"
val_dir = "/content/drive/MyDrive/Projects/ddib-main/ddib-main/ILSVRC2012_img_val"

MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
# 运行脚本
!python /content/drive/MyDrive/Projects/ddib-main/ddib-main/scripts/imagenet_translation.py $MODEL_FLAGS --classifier_scale 1.0 --model_path {model_path} --classifier_path {classifier_path} --val_dir {val_dir} --source 260,261 --target 261,262